name: PrefixShop
authors: [MountCloud]
website: http://www.mountcloud.org
description: PrefixShop is a plugin for the player name prefix shop.

#使用mc-plugin-common必须设置依赖关系为 [McPluginCommon]，use mc-plugin-common must set the dependency [McPluginCommon]
depend: [McPluginCommon]

main: org.mountcloud.mcplugin.prefixshop.PrefixShopPluginMain
version: 1.0
commands:
 prefixshop:
  description: prefix shop
  usage: /prefixshop